"""Static company name lookup for S&P 100 tickers.

No API calls — same static approach as the universe file.
"""

COMPANY_NAMES = {
    "AAPL": "Apple Inc.",
    "ABBV": "AbbVie Inc.",
    "ABT": "Abbott Laboratories",
    "ACN": "Accenture plc",
    "ADBE": "Adobe Inc.",
    "AIG": "American International Group",
    "AMD": "Advanced Micro Devices",
    "AMGN": "Amgen Inc.",
    "AMT": "American Tower Corp.",
    "AMZN": "Amazon.com Inc.",
    "AVGO": "Broadcom Inc.",
    "AXP": "American Express Co.",
    "BA": "Boeing Co.",
    "BAC": "Bank of America Corp.",
    "BK": "Bank of New York Mellon",
    "BKNG": "Booking Holdings Inc.",
    "BLK": "BlackRock Inc.",
    "BMY": "Bristol-Myers Squibb",
    "BRK.B": "Berkshire Hathaway Inc.",
    "C": "Citigroup Inc.",
    "CAT": "Caterpillar Inc.",
    "CHTR": "Charter Communications",
    "CL": "Colgate-Palmolive Co.",
    "CMCSA": "Comcast Corp.",
    "COF": "Capital One Financial",
    "COP": "ConocoPhillips",
    "COST": "Costco Wholesale Corp.",
    "CRM": "Salesforce Inc.",
    "CSCO": "Cisco Systems Inc.",
    "CVS": "CVS Health Corp.",
    "CVX": "Chevron Corp.",
    "DE": "Deere & Company",
    "DHR": "Danaher Corp.",
    "DIS": "Walt Disney Co.",
    "DUK": "Duke Energy Corp.",
    "EMR": "Emerson Electric Co.",
    "ETN": "Eaton Corp.",
    "EXC": "Exelon Corp.",
    "F": "Ford Motor Co.",
    "FDX": "FedEx Corp.",
    "GD": "General Dynamics Corp.",
    "GE": "GE Aerospace",
    "GILD": "Gilead Sciences Inc.",
    "GM": "General Motors Co.",
    "GOOG": "Alphabet Inc. (Class C)",
    "GOOGL": "Alphabet Inc. (Class A)",
    "GS": "Goldman Sachs Group",
    "HD": "Home Depot Inc.",
    "HON": "Honeywell International",
    "IBM": "International Business Machines",
    "INTC": "Intel Corp.",
    "INTU": "Intuit Inc.",
    "JNJ": "Johnson & Johnson",
    "JPM": "JPMorgan Chase & Co.",
    "KHC": "Kraft Heinz Co.",
    "KO": "Coca-Cola Co.",
    "LIN": "Linde plc",
    "LLY": "Eli Lilly and Co.",
    "LMT": "Lockheed Martin Corp.",
    "LOW": "Lowe's Companies Inc.",
    "MA": "Mastercard Inc.",
    "MCD": "McDonald's Corp.",
    "MDLZ": "Mondelez International",
    "MDT": "Medtronic plc",
    "MET": "MetLife Inc.",
    "META": "Meta Platforms Inc.",
    "MMM": "3M Company",
    "MO": "Altria Group Inc.",
    "MRK": "Merck & Co. Inc.",
    "MS": "Morgan Stanley",
    "MSFT": "Microsoft Corp.",
    "NEE": "NextEra Energy Inc.",
    "NFLX": "Netflix Inc.",
    "NKE": "Nike Inc.",
    "NOW": "ServiceNow Inc.",
    "NVDA": "NVIDIA Corp.",
    "ORCL": "Oracle Corp.",
    "PEP": "PepsiCo Inc.",
    "PFE": "Pfizer Inc.",
    "PG": "Procter & Gamble Co.",
    "PM": "Philip Morris International",
    "PYPL": "PayPal Holdings Inc.",
    "QCOM": "Qualcomm Inc.",
    "RTX": "RTX Corp.",
    "SBUX": "Starbucks Corp.",
    "SCHW": "Charles Schwab Corp.",
    "SO": "Southern Company",
    "SPG": "Simon Property Group",
    "T": "AT&T Inc.",
    "TGT": "Target Corp.",
    "TMO": "Thermo Fisher Scientific",
    "TMUS": "T-Mobile US Inc.",
    "TXN": "Texas Instruments Inc.",
    "UNH": "UnitedHealth Group Inc.",
    "UNP": "Union Pacific Corp.",
    "UPS": "United Parcel Service",
    "USB": "U.S. Bancorp",
    "V": "Visa Inc.",
    "VZ": "Verizon Communications",
    "WFC": "Wells Fargo & Co.",
    "WMT": "Walmart Inc.",
    "XOM": "Exxon Mobil Corp.",
}


def get_company_name(ticker: str) -> str:
    """Return the company name for a ticker, or the ticker itself if not found."""
    return COMPANY_NAMES.get(ticker, ticker)
