"""GICS sector mapping for S&P 100 constituents.

Cross-referenced with src/universe/sp100.py for complete coverage.
"""

SECTOR_MAP: dict[str, str] = {
    # Information Technology
    "AAPL": "Technology",
    "ACN": "Technology",
    "ADBE": "Technology",
    "AMD": "Technology",
    "AVGO": "Technology",
    "CRM": "Technology",
    "CSCO": "Technology",
    "INTC": "Technology",
    "INTU": "Technology",
    "MSFT": "Technology",
    "NOW": "Technology",
    "NVDA": "Technology",
    "ORCL": "Technology",
    "QCOM": "Technology",
    "TXN": "Technology",
    # Communication Services
    "CHTR": "Communication Services",
    "CMCSA": "Communication Services",
    "DIS": "Communication Services",
    "GOOG": "Communication Services",
    "GOOGL": "Communication Services",
    "META": "Communication Services",
    "NFLX": "Communication Services",
    "T": "Communication Services",
    "TMUS": "Communication Services",
    "VZ": "Communication Services",
    # Consumer Discretionary
    "AMZN": "Consumer Discretionary",
    "BKNG": "Consumer Discretionary",
    "F": "Consumer Discretionary",
    "GM": "Consumer Discretionary",
    "HD": "Consumer Discretionary",
    "LOW": "Consumer Discretionary",
    "MCD": "Consumer Discretionary",
    "NKE": "Consumer Discretionary",
    "SBUX": "Consumer Discretionary",
    "TGT": "Consumer Discretionary",
    # Consumer Staples
    "CL": "Consumer Staples",
    "COST": "Consumer Staples",
    "KHC": "Consumer Staples",
    "KO": "Consumer Staples",
    "MDLZ": "Consumer Staples",
    "MO": "Consumer Staples",
    "PEP": "Consumer Staples",
    "PG": "Consumer Staples",
    "PM": "Consumer Staples",
    "WMT": "Consumer Staples",
    # Health Care
    "ABBV": "Health Care",
    "ABT": "Health Care",
    "AMGN": "Health Care",
    "BMY": "Health Care",
    "CVS": "Health Care",
    "DHR": "Health Care",
    "GILD": "Health Care",
    "JNJ": "Health Care",
    "LLY": "Health Care",
    "MDT": "Health Care",
    "MRK": "Health Care",
    "PFE": "Health Care",
    "TMO": "Health Care",
    "UNH": "Health Care",
    # Financials
    "AIG": "Financials",
    "AXP": "Financials",
    "BAC": "Financials",
    "BK": "Financials",
    "BLK": "Financials",
    "BRK.B": "Financials",
    "C": "Financials",
    "COF": "Financials",
    "GS": "Financials",
    "JPM": "Financials",
    "MET": "Financials",
    "MS": "Financials",
    "PYPL": "Financials",
    "SCHW": "Financials",
    "USB": "Financials",
    "WFC": "Financials",
    "MA": "Financials",
    "V": "Financials",
    "IBM": "Technology",
    # Industrials
    "BA": "Industrials",
    "CAT": "Industrials",
    "DE": "Industrials",
    "EMR": "Industrials",
    "ETN": "Industrials",
    "FDX": "Industrials",
    "GD": "Industrials",
    "GE": "Industrials",
    "HON": "Industrials",
    "LMT": "Industrials",
    "MMM": "Industrials",
    "RTX": "Industrials",
    "UNP": "Industrials",
    "UPS": "Industrials",
    # Energy
    "COP": "Energy",
    "CVX": "Energy",
    "XOM": "Energy",
    # Materials
    "LIN": "Materials",
    # Utilities
    "DUK": "Utilities",
    "EXC": "Utilities",
    "NEE": "Utilities",
    "SO": "Utilities",
    # Real Estate
    "AMT": "Real Estate",
    "SPG": "Real Estate",
}
